/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOfficerDashboardRouteImport } from './routes/_authenticated/officer/dashboard'
import { Route as AuthenticatedOfficerApplicationsRouteImport } from './routes/_authenticated/officer/applications'
import { Route as AuthenticatedCitizenDashboardRouteImport } from './routes/_authenticated/citizen/dashboard'
import { Route as AuthenticatedCitizenApplyRouteImport } from './routes/_authenticated/citizen/apply'
import { Route as AuthenticatedAdminWorkflowsRouteImport } from './routes/_authenticated/admin/workflows'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated/admin/services'
import { Route as AuthenticatedAdminOfficersRouteImport } from './routes/_authenticated/admin/officers'
import { Route as AuthenticatedAdminAuditLogsRouteImport } from './routes/_authenticated/admin/audit-logs'
import { Route as AuthenticatedOfficerReviewIdRouteImport } from './routes/_authenticated/officer/review.$id'
import { Route as AuthenticatedCitizenApplicationsIdRouteImport } from './routes/_authenticated/citizen/applications.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOfficerDashboardRoute =
  AuthenticatedOfficerDashboardRouteImport.update({
    id: '/officer/dashboard',
    path: '/officer/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOfficerApplicationsRoute =
  AuthenticatedOfficerApplicationsRouteImport.update({
    id: '/officer/applications',
    path: '/officer/applications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCitizenDashboardRoute =
  AuthenticatedCitizenDashboardRouteImport.update({
    id: '/citizen/dashboard',
    path: '/citizen/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCitizenApplyRoute =
  AuthenticatedCitizenApplyRouteImport.update({
    id: '/citizen/apply',
    path: '/citizen/apply',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminWorkflowsRoute =
  AuthenticatedAdminWorkflowsRouteImport.update({
    id: '/admin/workflows',
    path: '/admin/workflows',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/admin/services',
    path: '/admin/services',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminOfficersRoute =
  AuthenticatedAdminOfficersRouteImport.update({
    id: '/admin/officers',
    path: '/admin/officers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAuditLogsRoute =
  AuthenticatedAdminAuditLogsRouteImport.update({
    id: '/admin/audit-logs',
    path: '/admin/audit-logs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOfficerReviewIdRoute =
  AuthenticatedOfficerReviewIdRouteImport.update({
    id: '/officer/review/$id',
    path: '/officer/review/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCitizenApplicationsIdRoute =
  AuthenticatedCitizenApplicationsIdRouteImport.update({
    id: '/citizen/applications/$id',
    path: '/citizen/applications/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/officers': typeof AuthenticatedAdminOfficersRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/workflows': typeof AuthenticatedAdminWorkflowsRoute
  '/citizen/apply': typeof AuthenticatedCitizenApplyRoute
  '/citizen/dashboard': typeof AuthenticatedCitizenDashboardRoute
  '/officer/applications': typeof AuthenticatedOfficerApplicationsRoute
  '/officer/dashboard': typeof AuthenticatedOfficerDashboardRoute
  '/citizen/applications/$id': typeof AuthenticatedCitizenApplicationsIdRoute
  '/officer/review/$id': typeof AuthenticatedOfficerReviewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/officers': typeof AuthenticatedAdminOfficersRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/workflows': typeof AuthenticatedAdminWorkflowsRoute
  '/citizen/apply': typeof AuthenticatedCitizenApplyRoute
  '/citizen/dashboard': typeof AuthenticatedCitizenDashboardRoute
  '/officer/applications': typeof AuthenticatedOfficerApplicationsRoute
  '/officer/dashboard': typeof AuthenticatedOfficerDashboardRoute
  '/citizen/applications/$id': typeof AuthenticatedCitizenApplicationsIdRoute
  '/officer/review/$id': typeof AuthenticatedOfficerReviewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/_authenticated/admin/officers': typeof AuthenticatedAdminOfficersRoute
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRoute
  '/_authenticated/admin/workflows': typeof AuthenticatedAdminWorkflowsRoute
  '/_authenticated/citizen/apply': typeof AuthenticatedCitizenApplyRoute
  '/_authenticated/citizen/dashboard': typeof AuthenticatedCitizenDashboardRoute
  '/_authenticated/officer/applications': typeof AuthenticatedOfficerApplicationsRoute
  '/_authenticated/officer/dashboard': typeof AuthenticatedOfficerDashboardRoute
  '/_authenticated/citizen/applications/$id': typeof AuthenticatedCitizenApplicationsIdRoute
  '/_authenticated/officer/review/$id': typeof AuthenticatedOfficerReviewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin/audit-logs'
    | '/admin/officers'
    | '/admin/services'
    | '/admin/workflows'
    | '/citizen/apply'
    | '/citizen/dashboard'
    | '/officer/applications'
    | '/officer/dashboard'
    | '/citizen/applications/$id'
    | '/officer/review/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin/audit-logs'
    | '/admin/officers'
    | '/admin/services'
    | '/admin/workflows'
    | '/citizen/apply'
    | '/citizen/dashboard'
    | '/officer/applications'
    | '/officer/dashboard'
    | '/citizen/applications/$id'
    | '/officer/review/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/admin/audit-logs'
    | '/_authenticated/admin/officers'
    | '/_authenticated/admin/services'
    | '/_authenticated/admin/workflows'
    | '/_authenticated/citizen/apply'
    | '/_authenticated/citizen/dashboard'
    | '/_authenticated/officer/applications'
    | '/_authenticated/officer/dashboard'
    | '/_authenticated/citizen/applications/$id'
    | '/_authenticated/officer/review/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/officer/dashboard': {
      id: '/_authenticated/officer/dashboard'
      path: '/officer/dashboard'
      fullPath: '/officer/dashboard'
      preLoaderRoute: typeof AuthenticatedOfficerDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/officer/applications': {
      id: '/_authenticated/officer/applications'
      path: '/officer/applications'
      fullPath: '/officer/applications'
      preLoaderRoute: typeof AuthenticatedOfficerApplicationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/citizen/dashboard': {
      id: '/_authenticated/citizen/dashboard'
      path: '/citizen/dashboard'
      fullPath: '/citizen/dashboard'
      preLoaderRoute: typeof AuthenticatedCitizenDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/citizen/apply': {
      id: '/_authenticated/citizen/apply'
      path: '/citizen/apply'
      fullPath: '/citizen/apply'
      preLoaderRoute: typeof AuthenticatedCitizenApplyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/workflows': {
      id: '/_authenticated/admin/workflows'
      path: '/admin/workflows'
      fullPath: '/admin/workflows'
      preLoaderRoute: typeof AuthenticatedAdminWorkflowsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/officers': {
      id: '/_authenticated/admin/officers'
      path: '/admin/officers'
      fullPath: '/admin/officers'
      preLoaderRoute: typeof AuthenticatedAdminOfficersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/audit-logs': {
      id: '/_authenticated/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/officer/review/$id': {
      id: '/_authenticated/officer/review/$id'
      path: '/officer/review/$id'
      fullPath: '/officer/review/$id'
      preLoaderRoute: typeof AuthenticatedOfficerReviewIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/citizen/applications/$id': {
      id: '/_authenticated/citizen/applications/$id'
      path: '/citizen/applications/$id'
      fullPath: '/citizen/applications/$id'
      preLoaderRoute: typeof AuthenticatedCitizenApplicationsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminAuditLogsRoute: typeof AuthenticatedAdminAuditLogsRoute
  AuthenticatedAdminOfficersRoute: typeof AuthenticatedAdminOfficersRoute
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRoute
  AuthenticatedAdminWorkflowsRoute: typeof AuthenticatedAdminWorkflowsRoute
  AuthenticatedCitizenApplyRoute: typeof AuthenticatedCitizenApplyRoute
  AuthenticatedCitizenDashboardRoute: typeof AuthenticatedCitizenDashboardRoute
  AuthenticatedOfficerApplicationsRoute: typeof AuthenticatedOfficerApplicationsRoute
  AuthenticatedOfficerDashboardRoute: typeof AuthenticatedOfficerDashboardRoute
  AuthenticatedCitizenApplicationsIdRoute: typeof AuthenticatedCitizenApplicationsIdRoute
  AuthenticatedOfficerReviewIdRoute: typeof AuthenticatedOfficerReviewIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminAuditLogsRoute: AuthenticatedAdminAuditLogsRoute,
  AuthenticatedAdminOfficersRoute: AuthenticatedAdminOfficersRoute,
  AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRoute,
  AuthenticatedAdminWorkflowsRoute: AuthenticatedAdminWorkflowsRoute,
  AuthenticatedCitizenApplyRoute: AuthenticatedCitizenApplyRoute,
  AuthenticatedCitizenDashboardRoute: AuthenticatedCitizenDashboardRoute,
  AuthenticatedOfficerApplicationsRoute: AuthenticatedOfficerApplicationsRoute,
  AuthenticatedOfficerDashboardRoute: AuthenticatedOfficerDashboardRoute,
  AuthenticatedCitizenApplicationsIdRoute:
    AuthenticatedCitizenApplicationsIdRoute,
  AuthenticatedOfficerReviewIdRoute: AuthenticatedOfficerReviewIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
